### ISSUE TITLE
Cannot publish

### ISSUE THREAD

**Issue by manveru** [sandro/bench_press#3]
I'm on Archlinux with Ruby 1.9.1.
After applying the patch in my fork: http://github.com/manveru/bench_press/commit/e0ff0dbbe752787cef5de6de2157f7f19bd4d578
I get this error when trying to publish.
Haven't digged much further, might be an issue with Facter instead.

```
/home/manveru/github/manveru/bench_press/lib/bench_press/system_information.rb:34:in `digest': can't convert nil into String (TypeError)
  from /home/manveru/github/manveru/bench_press/lib/bench_press/system_information.rb:34:in `hexdigest'
  from /home/manveru/github/manveru/bench_press/lib/bench_press/system_information.rb:34:in `crypted_identifier'
  from /home/manveru/github/manveru/bench_press/lib/bench_press/report.rb:42:in `to_hash'
  from /home/manveru/github/manveru/bench_press/lib/bench_press/ruby_benchmark.rb:9:in `publish'
  from /home/manveru/github/manveru/bench_press/lib/bench_press/cli.rb:92:in `publish'
  from /home/manveru/github/manveru/bench_press/lib/bench_press/cli.rb:68:in `perform_bench_press'
  from /home/manveru/github/manveru/bench_press/lib/bench_press/cli.rb:55:in `run'
  from /home/manveru/github/manveru/bench_press/bin/bench_press:4:in `<main>'
zsh: exit 1     ~/github/manveru/bench_press/bin/bench_press -p sum.rb
```

**Comment by sandro** [comment]
Crap! Guess I removed activesupport too hastily. I'll have a look at the 1.9 issue as soon as possible, thanks.
